before_install: gem install bundler -v 1.12.5
cache: bundler
gemfile:
  - gemfiles/faraday_0.8.gemfile
  - gemfiles/faraday_0.9.gemfile
  - gemfiles/faraday_release.gemfile
  - gemfiles/faraday_canary.gemfile
language: ruby
matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/faraday_canary.gemfile
notifications:
  email: false
rvm:
  - 2.3.1
sudo: false
