before_install: gem install bundler -v 1.12.5
cache: bundler
gemfile:
  - gemfiles/faraday_0.8.gemfile
  - gemfiles/faraday_0.9.gemfile
  - gemfiles/faraday_0.10.gemfile
  - gemfiles/faraday_canary.gemfile
language: ruby
matrix:
  fast_finish: true
  allow_failures:
    - gemfile: gemfiles/faraday_canary.gemfile
notifications:
  email: false
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
sudo: false
