before_install: gem install bundler -v 1.16.1
before_script:
  - bundle exec license_finder licenses add bundler MIT
cache:
  bundler: true
gemfile:
  - gemfiles/faraday_0.8.gemfile
  - gemfiles/faraday_0.12.gemfile
  - gemfiles/faraday_0.13.gemfile
  - gemfiles/faraday_0.14.gemfile
  - gemfiles/faraday_0.15.gemfile
  - gemfiles/faraday_canary.gemfile
language: ruby
matrix:
  allow_failures:
    - gemfile: gemfiles/faraday_canary.gemfile
  fast_finish: true
notifications:
  email: false
script:
  - bundle exec license_finder --quiet
  - bundle exec rake
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
sudo: false
