---

before_install:
  - "gem install bundler -v 2.1.3"
before_script:
  - "bundle exec license_finder licenses add bundler MIT"
branches:
  only:
    - "master"
    - '/^v\d+\.\d+\.\d+/'
cache:
  bundler: true
dist: "bionic"
jobs:
  allow_failures:
    - gemfile: "gemfiles/faraday_canary.gemfile"

  fail_fast: true

  include:
    - stage: "Test"

    - stage: "Latest Faraday Release"
      gemfile: "gemfiles/faraday_latest.gemfile"

    - gemfile: "gemfiles/faraday_0.8.gemfile"
      stage: "Additional Faraday Tests"
    - gemfile: "gemfiles/faraday_0.x.gemfile"
    - gemfile: "gemfiles/faraday_1.x.gemfile"
    - gemfile: "gemfiles/faraday_canary.gemfile"
language: "ruby"
notifications:
  email: false
rvm:
  - "2.7.0"
script:
  - "bundle exec rubocop -fq"
  - "bundle exec license_finder --quiet"
  - "bundle exec rake"
